# Documentation
# https://docs.docker.com/compose/compose-file

version: "3"

services:
  app:
    image: "mainapi"
    build: .
    container_name: "mainapi"
    restart: "always"
    volumes:
      - "./src:/src"
    env_file:
      - "./.env.development"
    ports:
      - "3001:3001"
    extra_hosts:
      - "networklocalhost:192.168.0.13"
  #    links:
  #      - dbapp
  #    depends_on:
  #      - dbapp
  #  dbapp:
  #    image: "mongo"
  #    container_name: "mongodatabase-app"
  #    ports:
  #      - "27000:27017"
  #    volumes:
  #      - "./.docker/mongodb:/data/db"
  nginx:
    image: "mainapi-nginx"
    build: "./.docker/nginx"
    container_name: "mainapi-nginx"
    restart: "always"
    ports:
      - "3000:3000"
    depends_on:
      - app
